// constants/countries.ts
// Full list of UN-recognised countries with ISO-3166-1 alpha-2 code and flag emoji.

export interface Country {
  code: string;
  name: string;
  flag: string;
}

// Flag emoji helper — converts ISO code to regional indicator characters
function flag(code: string): string {
  return code
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('');
}

function c(code: string, name: string): Country {
  return { code, name, flag: flag(code) };
}

export const COUNTRIES: Country[] = [
  // Most populous / commonly used first for faster lookup
  c('US', 'United States'),
  c('GB', 'United Kingdom'),
  c('CA', 'Canada'),
  c('AU', 'Australia'),
  c('NZ', 'New Zealand'),
  c('IN', 'India'),
  c('PK', 'Pakistan'),
  c('BD', 'Bangladesh'),
  c('NG', 'Nigeria'),
  c('ZA', 'South Africa'),
  c('KE', 'Kenya'),
  c('GH', 'Ghana'),
  c('ET', 'Ethiopia'),
  c('TZ', 'Tanzania'),
  c('UG', 'Uganda'),
  c('BR', 'Brazil'),
  c('MX', 'Mexico'),
  c('CO', 'Colombia'),
  c('AR', 'Argentina'),
  c('PE', 'Peru'),
  c('VE', 'Venezuela'),
  c('CL', 'Chile'),
  c('EC', 'Ecuador'),
  c('BO', 'Bolivia'),
  c('PY', 'Paraguay'),
  c('UY', 'Uruguay'),
  c('DE', 'Germany'),
  c('FR', 'France'),
  c('IT', 'Italy'),
  c('ES', 'Spain'),
  c('PT', 'Portugal'),
  c('NL', 'Netherlands'),
  c('BE', 'Belgium'),
  c('SE', 'Sweden'),
  c('NO', 'Norway'),
  c('DK', 'Denmark'),
  c('FI', 'Finland'),
  c('CH', 'Switzerland'),
  c('AT', 'Austria'),
  c('PL', 'Poland'),
  c('CZ', 'Czech Republic'),
  c('HU', 'Hungary'),
  c('RO', 'Romania'),
  c('GR', 'Greece'),
  c('TR', 'Turkey'),
  c('IE', 'Ireland'),
  c('RU', 'Russia'),
  c('UA', 'Ukraine'),
  c('CN', 'China'),
  c('JP', 'Japan'),
  c('KR', 'South Korea'),
  c('TH', 'Thailand'),
  c('VN', 'Vietnam'),
  c('PH', 'Philippines'),
  c('MY', 'Malaysia'),
  c('SG', 'Singapore'),
  c('ID', 'Indonesia'),
  c('MM', 'Myanmar'),
  c('KH', 'Cambodia'),
  c('LA', 'Laos'),
  c('NP', 'Nepal'),
  c('LK', 'Sri Lanka'),
  c('AF', 'Afghanistan'),
  c('IQ', 'Iraq'),
  c('IR', 'Iran'),
  c('SA', 'Saudi Arabia'),
  c('AE', 'United Arab Emirates'),
  c('QA', 'Qatar'),
  c('KW', 'Kuwait'),
  c('BH', 'Bahrain'),
  c('OM', 'Oman'),
  c('JO', 'Jordan'),
  c('LB', 'Lebanon'),
  c('IL', 'Israel'),
  c('PS', 'Palestine'),
  c('YE', 'Yemen'),
  c('SY', 'Syria'),
  c('EG', 'Egypt'),
  c('LY', 'Libya'),
  c('TN', 'Tunisia'),
  c('DZ', 'Algeria'),
  c('MA', 'Morocco'),
  c('SD', 'Sudan'),
  c('SS', 'South Sudan'),
  c('SO', 'Somalia'),
  c('MZ', 'Mozambique'),
  c('ZM', 'Zambia'),
  c('ZW', 'Zimbabwe'),
  c('MW', 'Malawi'),
  c('CM', 'Cameroon'),
  c('CI', 'Côte d\'Ivoire'),
  c('SN', 'Senegal'),
  c('ML', 'Mali'),
  c('BF', 'Burkina Faso'),
  c('NE', 'Niger'),
  c('TD', 'Chad'),
  c('CF', 'Central African Republic'),
  c('CG', 'Republic of Congo'),
  c('CD', 'DR Congo'),
  c('RW', 'Rwanda'),
  c('BI', 'Burundi'),
  c('AO', 'Angola'),
  c('NA', 'Namibia'),
  c('BW', 'Botswana'),
  c('LS', 'Lesotho'),
  c('SZ', 'Eswatini'),
  c('MG', 'Madagascar'),
  c('MU', 'Mauritius'),
  c('MX', 'Mexico'),
  c('GT', 'Guatemala'),
  c('HN', 'Honduras'),
  c('SV', 'El Salvador'),
  c('NI', 'Nicaragua'),
  c('CR', 'Costa Rica'),
  c('PA', 'Panama'),
  c('CU', 'Cuba'),
  c('DO', 'Dominican Republic'),
  c('HT', 'Haiti'),
  c('JM', 'Jamaica'),
  c('TT', 'Trinidad and Tobago'),
  c('BB', 'Barbados'),
  c('GY', 'Guyana'),
  c('SR', 'Suriname'),
  c('PG', 'Papua New Guinea'),
  c('FJ', 'Fiji'),
  c('SB', 'Solomon Islands'),
  c('VU', 'Vanuatu'),
  c('TO', 'Tonga'),
  c('WS', 'Samoa'),
  c('KZ', 'Kazakhstan'),
  c('UZ', 'Uzbekistan'),
  c('TM', 'Turkmenistan'),
  c('KG', 'Kyrgyzstan'),
  c('TJ', 'Tajikistan'),
  c('AZ', 'Azerbaijan'),
  c('AM', 'Armenia'),
  c('GE', 'Georgia'),
  c('MD', 'Moldova'),
  c('BY', 'Belarus'),
  c('LT', 'Lithuania'),
  c('LV', 'Latvia'),
  c('EE', 'Estonia'),
  c('IS', 'Iceland'),
  c('LU', 'Luxembourg'),
  c('MT', 'Malta'),
  c('CY', 'Cyprus'),
  c('SK', 'Slovakia'),
  c('SI', 'Slovenia'),
  c('HR', 'Croatia'),
  c('BA', 'Bosnia and Herzegovina'),
  c('RS', 'Serbia'),
  c('ME', 'Montenegro'),
  c('MK', 'North Macedonia'),
  c('AL', 'Albania'),
  c('XK', 'Kosovo'),
  c('BG', 'Bulgaria'),
].sort((a, b) => a.name.localeCompare(b.name));
